### ISSUE TITLE
JSON quotes are escaped as `\"`

### ISSUE THREAD

**Issue by rmandvikar** [serilog-contrib/serilog-sinks-applicationinsights#117]
A json string was logged as below in v2.6.2:
```
{"prop":"value"}
```

But it's logged (looks like escaped) as below in v3.0.3:
```
{\"prop\":\"value\"}
```

This is in the `Custom Properties`. **To clarify**, I'm logging json request/response body as string. 

This looks like a bug to me. Is this intended?

**Comment by aloneguid** [comment]
https://github.com/serilog/serilog-sinks-applicationinsights#how-custom-properties-are-logged

**Comment by aloneguid** [comment]
Oh I see your point

**Comment by aloneguid** [comment]
@rmandvikar struggling here, i can't see quotes, can you provide a sample?

**Comment by rmandvikar** [comment]
Here is the trace log from application insights:

```
TRACE
Verbose

Trace Properties
  ...
  Event time        ...
  Device type       ...
  Message           ...
  Severity level    ...

Custom Properties

  SourceContext     ...
  MessageTemplate   ...
  MachineName       ...
  Application Name  ...
  ThreadId          ...
  ProcessId         ...
  RequestMethod     POST
  RequestUri        https://company.com/v1/app1
  RequestBody       {\"transactionId\":\"0be5b9c3-7d8b-44ee-a4cc-97ed833392ab\"}
  ResponseBody      {\"details\":\"ok\"}
  StatusCode        201
  ...
```
Before request and response were:
```
  RequestBody       {"transactionId":"0be5b9c3-7d8b-44ee-a4cc-97ed833392ab"}
  ResponseBody      {"details":"ok"}
```

Request / Response bodies are in json and are read as,
```
requestBody = request.Content.ReadAsStringAsync().ConfigureAwait(false);
responseBody = response.Content.ReadAsStringAsync().ConfigureAwait(false);
```

I'm using the same Microsoft.ApplicationInsights 2.9.1 package with v2.6.2 and v3.0.3 but I do not think (I'm not sure) the issue lies in there.

**Comment by rmandvikar** [comment]
Also please see my comment in issue https://github.com/serilog/serilog-sinks-applicationinsights/issues/95 about submitting a PR to also log `MessageTemplate` as I can't use v3.0.3 until this issue is fixed.

**Comment by aloneguid** [comment]
@rmandvikar sorry have you submitted a PR?

**Comment by rmandvikar** [comment]
@aloneguid I don't have a PR for this bug in v3.0.3, but I've a PR for fixing a different bug in 2.6.4 (tag v134) (see #95).

**Comment by aloneguid** [comment]
@rmandvikar there is no build/release pipeline for v2, you'll have to raise PR against master branch.

**Comment by rmandvikar** [comment]
@aloneguid I did (see pr https://github.com/serilog/serilog-sinks-applicationinsights/pull/120), but there are conflicts. How to address that?

**Comment by trungdang194** [comment]
got the same issue in version v3.10, revert to v2.6.2 then it work as expected, no escaped string

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!

**Comment by ohlus** [comment]
Hi, I'm commenting just to let you know that this is still a problem in the current version (3.1.0).

We're logging string properties containing JSON values and then querying those values using Kusto's `parse_json()` function, which fails due to the escaping.
This is our main problem. However, problematic are also regular string values of properties which are being unnecessarily escaped.

**Comment by nblumhardt** [comment]
Thanks :+1: this needs fixing, will label as up-for-grabs :+1:

**Comment by ohlus** [comment]
I just tried version `4.0.0-dev-00022` and everything looks fine now.

```csharp
Logger
.ForContext("PropertyRawJSON", "{ \"text\": \"raw JSON string\" }")
.ForContext("PropertyString", "just a normal \"\\\n{} string")
.ForContext("PropertyDestructured", new { text = "destructured object" }, destructureObjects: true)
.ForContext("PropertyDouble", 1234.5d)
.Information("TESTING Serilog.Sinks.ApplicationInsights: string \"\\ abcd PropertyTest: {PropertyTest}", "another normal \"\\\n string");
```

produced these values in Application Insights:

```
message: TESTING Serilog.Sinks.ApplicationInsights: string "\ abcd PropertyTest: another normal "\
string
customDimensions:
  MessageTemplate: TESTING Serilog.Sinks.ApplicationInsights: string "\ abcd PropertyTest: {PropertyTest}
  PropertyDestructured: {"text":"destructured object"}
  PropertyDouble: 1234.5
  PropertyRawJSON: { "text": "raw JSON string" }
  PropertyString: just a normal "\
{} string
  PropertyTest: another normal "\
 string
```

For comparison, version `3.1.0` produced these values:

```
message: TESTING Serilog.Sinks.ApplicationInsights: string "\ abcd PropertyTest: "another normal \"\
 string"
customDimensions:
  MessageTemplate: TESTING Serilog.Sinks.ApplicationInsights: string "\ abcd PropertyTest: {PropertyTest}
  PropertyDestructured: {"text":"destructured object"}
  PropertyDouble: 1234.5
  PropertyRawJSON: { \"text\": \"raw JSON string\" }
  PropertyString: just a normal \"\\\n{} string
  PropertyTest: another normal \"\\\n string
```

Thank you for this fix.
